import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ToastContainer } from "react-toastify";
import Image from "next/image";
import palma from "../icons/palmas.jpg";
import logo from "../icons/logo.svg";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nuna | Social Media",
  description: "Generated by create next app",
};

interface ToastProviderProps {
  children: React.ReactNode;
}

export default function ToastProvider({ children }: ToastProviderProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="icon" href="./logo_favicon.ico" sizes="" />

        <div className="flex flex-row h-screen w-screen">
          <Image src={palma} className="h-screen" alt="image" />
          <div className="flex flex-col justify-between py-10 px-15 flex-1">
            <Link href="/" className="inline-block">
              <Image src={logo} alt="image" width={80} />
            </Link>

            {children}

            <div className="flex items-center justify-between w-full">
              <p>
                reach us:{" "}
                <span className=" text-white/35">khamidov.ko@gmail.com</span>
              </p>
              <Link href="/terms">read our Philosophy</Link>
            </div>
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
