import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { ToastContainer } from "react-toastify";
import Image from "next/image";
import palma from "../icons/palmas.jpg";
import logo from "../icons/logo.svg";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nuna | Social Media",
  description: "Generated by create next app",
};

interface ToastProviderProps {
  children: React.ReactNode;
}

export default function ToastProvider({ children }: ToastProviderProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="icon" href="./logo_favicon.ico" sizes="any" />

        <div className="flex flex-row h-screen w-screen gap-16">
          <Image
            src={palma}
            className="h-screen w-2/3"
            alt="image"
            width={500}
            height={500}
          />
          <div className="container py-5">
            <Link href="/" className="mb-72 inline-block">
              <Image src={logo} alt="image" width={172} height={64} />
            </Link>

            {children}
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
