import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import { toast, ToastContainer } from "react-toastify";
import Sidebar from "./components/Sidebar";
import ReadOur from "./components/ReadOur";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nuna | Social Media",
  description: "Generated by create next app",
};

interface ToastProviderProps {
  children: React.ReactNode;
}

export default function ToastProvider({ children }: ToastProviderProps) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="icon" href="./logo_favicon.ico" sizes="any" />
        <ReadOur />
        <div className="flex">
          <Sidebar />
          {children}
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
